#!/bin/bash
# Radio script for raspberry by Jaufré aligé
# https://github.com/Jau-Al/radio-by-ssh
# v0.4

case $1 in
inter )	echo "Now Playing France inter"
	killall vlc	
	cvlc http://direct.franceinter.fr/live/franceinter-midfi.mp3 &
	;;
info )	echo "Now Playing France Info"
	killall vlc
	cvlc http://direct.franceinfo.fr/live/franceinfo-midfi.mp3 &
	;;
ouifm )	echo "Now Playing OuiFM"
	killall vlc
	cvlc http://broadcast.infomaniak.ch/ouifm-high.mp3.m3u &
	;;
ouifm-collector )	echo "Now Playing OuiFM Collector"
	killall vlc
	cvlc http://ouifm3.ice.infomaniak.ch/ouifm3.mp3 &
	;;
ouifm-blues )	echo "Now Playing OuiFM Blues"
	killall vlc
	cvlc http://ouifmbluesnrock.ice.infomaniak.ch/ouifmbluesnrock-128.mp3 &
	;;
nova )	echo "Now Playing Nova Classic Rock"
	killall vlc
	cvlc http://173.236.29.52/listen.pls &
	;;
rmf-hh )	echo "Now Playing RMF Hard and Heavy"
	killall vlc
	cvlc http://www.miastomuzyki.pl/n/rmfhardandheavy.pls &
	;;
rmf-cr	)	echo "Now Playing RMF Classic Rock"
	killall vlc
	cvlc http://www.miastomuzyki.pl/n/rmfclassicrock.pls &
	;;
rmf-bl  )       echo "Now Playing RMF Blues"
        killall vlc
        cvlc http://www.miastomuzyki.pl/n/rmfblues.pls &
        ;;
stop )	killall vlc
	;;
edit )  sudo nano /usr/bin/radio
	;;
backup ) echo "Backup into home dir"
	cp /usr/bin/radio ~
	;;
install	) echo "Install script in /usr/bin/radio"
	sudo cp radio /usr/bin/radio
	sudo chmod +x /usr/bin/radio
	;;
remove	) echo "Remove/désinstaller radio ? (y/N)"
	read YnAnswer
	YnAnswer=$(echo $YnAnswer | awk '{print tolower($0)}')
	case $YnAnswer in
		y)
		echo "Remove/désinstaller /usr/bin/radio"
		 sudo rm /usr/bin/radio
		;;
		*)echo "Annulé/Canceled"
		;;
	esac
	;;
*)	echo -e "Syntax : radio [station]\r
or : radio stop | edit | backup | remove \n
Radios :\r
	France Inter : inter \r
	France Info : info \r
	OuiFM : ouifm \r
	OuiFM Collector : ouifm-collector \r
	OuiFM blues : ouifm-blues\r
	Nova Classic Rock : nova\r
	RMF Hard and Hevy : rmf-hh\r
	RMF Classic Rock : rmf-cr\r
	RMF Blues : rmf-bl\n"
	;;
esac
